### ISSUE TITLE
unable to run a script

### ISSUE THREAD

**Issue by chamithchathuka** [cross-the-world/ssh-pipeline#2]
+++++++++++++++++++STARTING PIPELINES+++++++++++++++++++
+++++++++++++++++++Pipeline: RUNNING SSH+++++++++++++++++++
pwd && echo "hello" && sh ~/runscript.sh
Traceback (most recent call last):
  File "/opt/tools/app.py", line 87, in <module>
    ssh_process()
  File "/opt/tools/app.py", line 64, in ssh_process
    ssh.connect(INPUT_HOST, port=INPUT_PORT, username=INPUT_USER,
  File "/usr/local/lib/python3.8/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/local/lib/python3.8/site-packages/paramiko/client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by biel-correa** [comment]
@chamithchathuka can you provide your pipeline yml? Based on what you send the error is in the script that you wrote
